# Generated by Django 5.0.6 on 2025-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessgrouprightuser',
            name='access_group_right',
        ),
        migrations.AddField(
            model_name='accessgrouprightuser',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
