# Generated by Django 5.0.6 on 2024-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='role',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
