# Generated by Django 5.0.6 on 2025-06-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_accessgrouprightuser_access_group_right_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessgrouprightuser',
            name='user',
        ),
        migrations.AddField(
            model_name='accessgrouprightuser',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
