# Generated by Django 5.0.6 on 2025-07-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyprofile_logo'),
        ('users', '0002_remove_accessgrouprightuser_access_group_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='company_role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_tenant_user_role', to='companies.companyrole'),
        ),
    ]
