# Generated by Django 5.0.6 on 2024-09-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_tenantuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='role',
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='auth.group'),
        ),
    ]
