# Generated by Django 5.0.6 on 2025-06-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_accessgrouprightuser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
