# Generated by Django 5.1.2 on 2024-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tenantuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='user',
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
