# Generated by Django 5.1.2 on 2024-10-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tenantuser_user_tenantuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantuser',
            old_name='tenant_password',
            new_name='password',
        ),
    ]
