# Generated by Django 5.0.6 on 2025-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tenantuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
