# Generated by Django 5.0.6 on 2024-09-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_grouppermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupPermission',
        ),
    ]
