# Generated by Django 5.1.2 on 2024-10-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_grouppermission'),
    ]

    operations = [
    ]
