# Generated by Django 5.1.2 on 2024-10-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registration', '0003_tenant_created_by_tenant_is_verified_tenant_otp_and_more'),
        ('users', '0007_auto_20241030_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantuser',
            name='user',
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='registration.tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user_id',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='auth.group'),
        ),
    ]
