# Generated by Django 5.0.6 on 2024-10-29 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_delete_tenantuser'),
        ('users', '0007_tenantuser_tenant_tenantuser_tenant_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='registration.tenant'),
        ),
    ]
