# Generated by Django 5.0.6 on 2025-06-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_tenantuser_user_tenantuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
