# Generated by Django 5.0.6 on 2025-06-24 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_accessright_otp'),
        ('users', '0008_remove_tenantuser_user_tenantuser_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='signature',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='AccessGroupRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=20)),
                ('application', models.CharField(max_length=50, null=True)),
                ('application_module', models.CharField(max_length=50, null=True)),
                ('group_name', models.CharField(max_length=20)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('access_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.accessright')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGroupRightUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('access_group_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accessgroupright')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
