# Generated by Django 5.0.6 on 2025-06-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tenantuser_date_created_tenantuser_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='signature',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
