# Generated by Django 5.0.6 on 2024-10-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tenantuser_client_alter_tenantuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
