# Generated by Django 5.0.6 on 2025-06-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_tenantuser_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='user_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
