# Generated by Django 5.0.6 on 2025-06-23 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_application_applicationmodule_application'),
        ('users', '0012_tenantuser_user_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroupRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=20)),
                ('group_name', models.CharField(max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('access_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.accessright')),
                ('application_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.applicationmodule')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGroupRightUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('access_group_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accessgroupright')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
