# Generated by Django 5.0.6 on 2025-06-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_applicationmodule_application'),
        ('users', '0013_accessgroupright_accessgrouprightuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgroupright',
            name='application_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_rights', to='registration.applicationmodule'),
        ),
    ]
