# Generated by Django 5.0.6 on 2025-06-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_accessgroupright_application_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgroupright',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessgrouprightuser',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
