# Generated by Django 5.0.6 on 2024-10-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_tenantuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
