# Generated by Django 5.0.6 on 2025-06-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_applicationmodule_application'),
        ('users', '0015_accessgroupright_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessgroupright',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_group', to='registration.application'),
        ),
    ]
