# Generated by Django 5.0.6 on 2025-06-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_accessgroupright_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgroupright',
            name='application',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accessgroupright',
            name='application_module',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
