version: '3.8'

services:
  server:
    build: .
    container_name: fastra-web
    hostname: server
    command: bash -c "python /app/wait_for_postgres.py && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - /opt/fastra-backend:/app
      - /opt/fastra-backend/staticfiles:/app/staticfiles
      - /opt/fastra-backend/media:/app/media
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
    networks:
      - app_network
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: fastra-nginx
    volumes:
      - /opt/fastra-backend/staticfiles:/opt/fastra-backend/staticfiles
      - /opt/fastra-backend/media:/opt/fastra-backend/media
      - /etc/nginx/sites-enabled/fastra-backend.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
