version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastra_backend
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  static_volume:
  media_volume:
