# Generated by Django 5.0.6 on 2025-07-23 14:14

import django_ckeditor_5.fields
import purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('product_category', models.CharField(choices=[('consumable', 'Consumable'), ('stockable', 'Stockable'), ('service-product', 'Service Product')], max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_po_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting Goods'), ('completed', 'Order Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_terms', models.CharField(blank=True, null=True)),
                ('purchase_policy', models.CharField(blank=True, null=True)),
                ('invoice_policy', models.CharField(blank=True, null=True)),
                ('delivery_terms', models.CharField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_pr_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('purpose', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_rfq_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='draft', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True)),
                ('unit_symbol', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('unit_category', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['is_hidden', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100, unique=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('currency_symbol', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['is_hidden', '-created_on'],
                'unique_together': {('currency_name', 'currency_code')},
            },
        ),
    ]
