# Generated by Django 5.1.2 on 2024-10-29 05:21

import django.db.models.deletion
import django_ckeditor_5.fields
import purchase.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-id'],
            },
        ),
        migrations.CreateModel(
            name='POVendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('product_category', models.CharField(choices=[('consumable', 'Consumable'), ('stockable', 'Stockable'), ('service-product', 'Service Product')], max_length=64)),
                ('available_product_quantity', models.PositiveIntegerField(default=0, verbose_name='Available Product Quantity')),
                ('total_quantity_purchased', models.PositiveIntegerField(default=0, verbose_name='Total Quantity Purchased')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_po_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting Goods'), ('completed', 'Order Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['is_hidden', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='vendor_profiles/')),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='POVendorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po_vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.povendorquote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
            ],
        ),
        migrations.AddField(
            model_name='povendorquote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='purchase.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_pr_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('purpose', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('suggested_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor')),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaserequest')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_rfq_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='draft', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaserequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor')),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
                ('request_for_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.requestforquotation')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='purchase.requestforquotation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_quotes', to='purchase.vendor')),
            ],
            options={
                'ordering': ['is_hidden', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='RFQVendorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
                ('rfq_vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.rfqvendorquote')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='povendorquote',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_quotes', to='purchase.vendor'),
        ),
    ]
