# Generated by Django 5.0.6 on 2025-07-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
