# Generated by Django 5.0.6 on 2024-07-18 07:21

import django.db.models.deletion
import django_ckeditor_5.fields
import purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POVendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_quotes', to='purchase.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='POVendorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po_vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.povendorquote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=purchase.models.generate_unique_po_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting', 'Awaiting Goods'), ('completed', 'Order Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=200)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('po_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='purchase.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='povendorquote',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='purchase.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RFQVendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='purchase.requestforquotation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_quotes', to='purchase.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RFQVendorQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='QTY')),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product')),
                ('rfq_vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.rfqvendorquote')),
            ],
        ),
    ]
