# Generated by Django 5.0.6 on 2024-09-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.DeleteModel(
            name='VendorCategory',
        ),
    ]
