# Generated by Django 5.0.6 on 2025-07-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchase', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchase.currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='purchase.currency'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requesting_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaserequest'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='purchase.currency'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='related_rfq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='purchase.requestforquotation'),
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.product'),
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='request_for_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.requestforquotation'),
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('unit_name', 'unit_category')},
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchase.vendor'),
        ),
    ]
