# Generated by Django 5.0.6 on 2024-09-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_vendor_category_delete_vendorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profiles/'),
        ),
    ]
