# Generated by Django 5.0.6 on 2024-07-28 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_povendorquote_povendorquoteitem_purchaseorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povendorquote',
            name='quote_total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_total_price',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='rfq_total_price',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquote',
            name='quote_total_price',
        ),
        migrations.AddField(
            model_name='rfqvendorquote',
            name='date_opened',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfqvendorquote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
