# Generated by Django 5.0.6 on 2025-07-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='total_price',
        ),
        migrations.AlterUniqueTogether(
            name='requestforquotationitem',
            unique_together={('request_for_quotation', 'product')},
        ),
    ]
