# Generated by Django 5.0.6 on 2025-07-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_vendor_profile_picture'),
        ('users', '0003_tenantuser_company_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='users.tenantuser'),
        ),
    ]
