# Generated by Django 5.0.6 on 2025-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_purchaserequestitem_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='estimated_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requestforquotationitem',
            name='estimated_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
