# Generated by Django 5.0.6 on 2025-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseorder_created_by_purchaserequest_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_product_quantity',
        ),
        migrations.AlterField(
            model_name='requestforquotationitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
