# Generated by Django 5.0.6 on 2024-07-29 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_department_is_hidden_povendorquote_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['is_hidden', '-id']},
        ),
        migrations.AlterModelOptions(
            name='povendorquote',
            options={'ordering': ['is_hidden', '-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['is_hidden', '-created_on']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['is_hidden', '-updated_on'], 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['is_hidden', '-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['is_hidden', '-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestitem',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='requestforquotation',
            options={'ordering': ['is_hidden', '-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='requestforquotationitem',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='rfqvendorquote',
            options={'ordering': ['is_hidden', '-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['is_hidden', '-created_on'], 'verbose_name_plural': 'Units of Measure'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['is_hidden', '-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='vendorcategory',
            options={'ordering': ['is_hidden', '-updated_on'], 'verbose_name_plural': 'Vendor Categories'},
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='requestforquotation',
            old_name='date_opened',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='povendorquote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='povendorquote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
