# Generated by Django 5.0.6 on 2025-07-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_product_available_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='unit_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('currency_name', 'currency_code')},
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('unit_name', 'unit_category')},
        ),
    ]
