# Generated by Django 5.0.6 on 2024-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchaserequest_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
