# Generated by Django 5.0.6 on 2025-08-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchaserequestitem_estimated_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='requestforquotationitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='requestforquotationitem',
            name='unit_of_measure',
        ),
    ]
