# Generated by Django 5.0.6 on 2024-09-28 21:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='requestforquotationitem',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='available_product_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Available Product Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('consumables', 'Consumables'), ('stockable', 'Stockable'), ('service-product', 'Service Product')], default='consumables', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity_purchased',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Quantity Purchased'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaserequest'),
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='actual_unit_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestforquotationitem',
            name='estimated_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
