# Generated by Django 5.0.6 on 2025-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_currency_currency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_quantity_purchased',
        ),
    ]
