# Generated by Django 5.0.6 on 2024-08-02 14:02

import purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_department_options_alter_povendorquote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforquotation',
            name='id',
            field=models.CharField(default=purchase.models.generate_unique_rfq_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
