# Generated by Django 5.0.6 on 2024-09-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('stockable', 'Stockable'), ('service-product', 'Service Product')], max_length=64),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestforquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestforquotationitem',
            name='actual_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
