# Generated by Django 5.0.6 on 2024-10-27 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_currency_rename_name_unitofmeasure_unit_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='suggested_vendor',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='requestforquotationitem',
            name='actual_unit_price',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='purchase.currency'),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='purchase.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='purchase.currency'),
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='vendor_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='description',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestforquotationitem',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='purchase.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
