# Generated by Django 5.0.6 on 2025-03-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_rename_suggested_vendor_purchaserequest_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requester',
        ),
    ]
