# Generated by Django 5.0.6 on 2025-03-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_remove_purchaserequest_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
    ]
