# Generated by Django 5.0.6 on 2025-05-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_date_updated_alter_location_date_created_and_more'),
        ('purchase', '0011_remove_purchaseorder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_policy',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requesting_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location'),
        ),
    ]
