# Generated by Django 5.0.6 on 2025-06-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchaseorder_destination_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povendorquoteitem',
            name='po_vendor_quote',
        ),
        migrations.RemoveField(
            model_name='povendorquoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquote',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquote',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquoteitem',
            name='rfq_vendor_quote',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='vendor_category',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='related_rfq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='purchase.requestforquotation'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='unit_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='POVendorQuote',
        ),
        migrations.DeleteModel(
            name='POVendorQuoteItem',
        ),
        migrations.DeleteModel(
            name='RFQVendorQuote',
        ),
        migrations.DeleteModel(
            name='RFQVendorQuoteItem',
        ),
    ]
