# Generated by Django 5.0.6 on 2025-05-19 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchaseorder_destination_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='povendorquoteitem',
            name='po_vendor_quote',
        ),
        migrations.RemoveField(
            model_name='povendorquoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquote',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquote',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquoteitem',
            name='rfq_vendor_quote',
        ),
        migrations.RemoveField(
            model_name='rfqvendorquoteitem',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='related_rfq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order', to='purchase.requestforquotation'),
        ),
        migrations.DeleteModel(
            name='POVendorQuote',
        ),
        migrations.DeleteModel(
            name='POVendorQuoteItem',
        ),
        migrations.DeleteModel(
            name='RFQVendorQuote',
        ),
        migrations.DeleteModel(
            name='RFQVendorQuoteItem',
        ),
    ]
