# Generated by Django 5.0.6 on 2025-06-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_remove_povendorquoteitem_po_vendor_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforquotation',
            name='vendor_category',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='unit_symbol',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
