# Generated by Django 5.0.6 on 2024-11-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0009_rename_suggested_vendor_purchaserequest_vendor_and_more'),
        ('users', '0008_remove_tenantuser_user_tenantuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('date_created', models.DateTimeField(auto_created=True)),
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=4, unique=True)),
                ('location_name', models.CharField(max_length=50, unique=True)),
                ('location_type', models.CharField(choices=[('internal', 'Internal'), ('partner', 'Partner')], default='internal', max_length=10)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('location_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='users.tenantuser')),
                ('store_keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_locations', to='users.tenantuser')),
            ],
            options={
                'ordering': ['is_hidden', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(default='Stock Level Update', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('warehouse_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(editable=False, max_length=50)),
                ('current_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Current Quantity')),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adjusted Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.product')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_items', to='inventory.stockadjustment')),
            ],
            options={
                'verbose_name': 'Adjustment Line',
                'verbose_name_plural': 'Adjustment Lines',
            },
        ),
    ]
