# Generated by Django 5.0.6 on 2025-06-26 09:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('shipping_policy', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('ready', 'Ready'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_of_return', models.DateField(default=django.utils.timezone.now)),
                ('source_location', models.CharField(default=None, max_length=255, null=True)),
                ('reason_for_return', models.TextField()),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField()),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingInventoryRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingProduct',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('incoming_product_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(choices=[('vendor_receipt', 'Vendor Receipt'), ('manufacturing_receipt', 'Manufacturing Receipt'), ('internal_transfer', 'Internal Transfer'), ('returns', 'Returns'), ('scrap', 'Scrap')], default='vendor_receipt')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('canceled', 'Canceled')], default='draft', max_length=15)),
                ('is_validated', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IncomingProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expected Quantity')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Received')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('location_code', models.CharField(max_length=4, unique=True)),
                ('location_name', models.CharField(max_length=50, unique=True)),
                ('location_type', models.CharField(choices=[('internal', 'Internal'), ('partner', 'Partner')], default='internal', max_length=10)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_hidden', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MultiLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingInventoryRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnIncomingProduct',
            fields=[
                ('unique_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('reason_for_return', models.TextField()),
                ('returned_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnIncomingProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_be_returned', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('damage', 'Damage'), ('loss', 'Loss')], default='damage', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ScrapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Scrap Quantity')),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adjusted Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(default='Stock Level Update', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(editable=False, max_length=50)),
                ('current_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Current Quantity')),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adjusted Quantity')),
            ],
            options={
                'verbose_name': 'Adjustment Line',
                'verbose_name_plural': 'Adjustment Lines',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('move_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('RETURN', 'Return'), ('INTERNAL', 'Internal Transfer'), ('ADJUSTMENT', 'Inventory Adjustment')], max_length=10)),
                ('object_id', models.CharField(max_length=20)),
                ('source_document_id', models.CharField(help_text='Reference number of the source document', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('date_moved', models.DateTimeField(blank=True, help_text='Actual date when the stock movement occurred', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_deliver', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_items', to='inventory.deliveryorder')),
            ],
        ),
    ]
