# Generated by Django 5.0.6 on 2024-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='id_number',
            field=models.PositiveIntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
