# Generated by Django 5.0.6 on 2025-06-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderitem',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='purchase.product'),
        ),
        migrations.AddField(
            model_name='deliveryorderreturn',
            name='source_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_document', to='inventory.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliveryorderreturnitem',
            name='delivery_order_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_return_items', to='inventory.deliveryorderreturn'),
        ),
        migrations.AddField(
            model_name='deliveryorderreturnitem',
            name='returned_product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_items', to='purchase.product'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='backorder_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='inventory.incomingproduct'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='related_po',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_product', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products', to='purchase.vendor'),
        ),
        migrations.AddField(
            model_name='incomingproductitem',
            name='incoming_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_product_items', to='inventory.incomingproduct'),
        ),
        migrations.AddField(
            model_name='incomingproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_product_items', to='purchase.product'),
        ),
    ]
