# Generated by Django 5.0.6 on 2025-07-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_initial'),
        ('purchase', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='location',
            name='store_keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_locations', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products_to_destination', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='source_location',
            field=models.ForeignKey(default='SUPP00001', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products_from_source', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='deliveryorderreturn',
            name='return_warehouse_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_warehouse', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_orders', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='locationstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='locationstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='purchase.product'),
        ),
        migrations.AddField(
            model_name='returnincomingproduct',
            name='source_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_incoming_product', to='inventory.incomingproduct'),
        ),
        migrations.AddField(
            model_name='returnincomingproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_product_items', to='purchase.product'),
        ),
        migrations.AddField(
            model_name='returnincomingproductitem',
            name='return_incoming_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_incoming_product_items', to='inventory.returnincomingproduct'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='warehouse_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='scrapitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.product'),
        ),
        migrations.AddField(
            model_name='scrapitem',
            name='scrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_items', to='inventory.scrap'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='warehouse_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.product'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='stock_adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_items', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_created', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_moves', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_moved', to='users.tenantuser'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='purchase.product'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_moves', to='inventory.location'),
        ),
        migrations.AlterUniqueTogether(
            name='locationstock',
            unique_together={('location', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['content_type', 'object_id'], name='inventory_s_content_845c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['status', 'move_type'], name='inventory_s_status_375c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['date_moved'], name='inventory_s_date_mo_4f1a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['source_document_id'], name='inventory_s_source__af13fd_idx'),
        ),
    ]
