# Generated by Django 5.0.6 on 2024-11-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockadjustment_id_number_alter_stockadjustment_id'),
        ('purchase', '0009_rename_suggested_vendor_purchaserequest_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(default='Stock Level Update', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('warehouse_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location')),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ScrapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Scrap Quantity')),
                ('adjusted_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adjusted Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.product')),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_items', to='inventory.scrap')),
            ],
        ),
    ]
