# Generated by Django 5.0.6 on 2025-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapitem',
            name='adjusted_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Adjusted Quantity'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='current_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Quantity'),
        ),
        migrations.AlterField(
            model_name='scrapitem',
            name='scrap_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Scrap Quantity'),
        ),
    ]
