# Generated by Django 5.0.6 on 2025-04-10 14:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_scrap_scrapitem'),
        ('purchase', '0011_remove_purchaseorder_created_by'),
        ('users', '0008_remove_tenantuser_user_tenantuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInventoryRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingInventoryRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('move_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('RETURN', 'Return'), ('INTERNAL', 'Internal Transfer'), ('ADJUSTMENT', 'Inventory Adjustment')], max_length=10)),
                ('object_id', models.CharField(max_length=20)),
                ('source_document_id', models.CharField(help_text='Reference number of the source document', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('date_moved', models.DateTimeField(blank=True, help_text='Actual date when the stock movement occurred', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_created', to='users.tenantuser')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_moves', to='inventory.location')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_moved', to='users.tenantuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='purchase.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_moves', to='inventory.location')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='inventory_s_content_845c3d_idx'), models.Index(fields=['status', 'move_type'], name='inventory_s_status_375c3d_idx'), models.Index(fields=['date_moved'], name='inventory_s_date_mo_4f1a0f_idx'), models.Index(fields=['source_document_id'], name='inventory_s_source__af13fd_idx')],
            },
        ),
    ]
