# Generated by Django 5.0.6 on 2025-08-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
        ('purchase', '0003_remove_purchaserequestitem_total_price_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockmove',
            name='inventory_s_content_845c3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmove',
            name='inventory_s_status_375c3d_idx',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='status',
        ),
        migrations.AddField(
            model_name='stockmove',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_of_measures_stock_moves', to='purchase.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_type'], name='inventory_s_move_ty_0fa310_idx'),
        ),
    ]
