# Generated by Django 5.0.6 on 2025-08-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stockmove_inventory_s_content_845c3d_idx_and_more'),
        ('inventory', '0004_scrapitem_adjusted_quantity_and_more'),
    ]

    operations = [
    ]
