# Generated by Django 5.0.6 on 2025-07-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_deliveryorderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproduct',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products_to_destination', to='inventory.location'),
        ),
    ]
