# Generated by Django 5.0.6 on 2025-05-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_date_updated_alter_location_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='adjustment_type',
            field=models.CharField(choices=[('damage', 'Damage'), ('loss', 'Loss')], default='damage', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('shipping_policy', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('ready', 'Ready'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_orders', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.deliveryorder')),
            ],
        ),
    ]
