# Generated by Django 5.0.6 on 2025-08-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_merge_20250804_1526'),
        ('purchase', '0003_remove_purchaserequestitem_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingproduct',
            name='backorder_of',
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('backorder_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('receipt_type', models.CharField(choices=[('vendor_receipt', 'Vendor Receipt'), ('manufacturing_receipt', 'Manufacturing Receipt'), ('internal_transfer', 'Internal Transfer'), ('returns', 'Returns'), ('scrap', 'Scrap')], default='vendor_receipt')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('canceled', 'Canceled')], default='draft', max_length=15)),
                ('is_validated', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('backorder_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backorder', to='inventory.incomingproduct')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders_to_destination', to='inventory.location')),
                ('source_location', models.ForeignKey(default='SUPP00001', on_delete=django.db.models.deletion.PROTECT, related_name='backorders_from_source', to='inventory.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='purchase.vendor')),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BackOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expected Quantity')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Received')),
                ('backorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorder_items', to='inventory.backorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorder_items', to='purchase.product')),
            ],
        ),
    ]
