# Generated by Django 5.0.6 on 2025-07-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_incomingproduct_destination_location'),
        ('purchase', '0004_remove_product_available_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='purchase.product')),
            ],
            options={
                'unique_together': {('location', 'product')},
            },
        ),
    ]
