# Generated by Django 5.0.6 on 2025-05-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location_date_updated_alter_location_date_created_and_more'),
        ('purchase', '0012_purchaseorder_destination_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='adjustment_type',
            field=models.CharField(choices=[('damage', 'Damage'), ('loss', 'Loss')], default='damage', max_length=20),
        ),
        migrations.CreateModel(
            name='IncomingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('vendor_receipt', 'Vendor Receipt'), ('manufacturing', 'Manufacturing'), ('internal_transfer', 'Internal Transfer'), ('returns', 'Returns')], default='vendor_receipt')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products_from_destination', to='inventory.location')),
                ('related_po', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_product', to='purchase.purchaseorder')),
                ('source_location', models.ForeignKey(default='SUPP00001', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products_from_source', to='inventory.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products', to='purchase.vendor')),
            ],
            options={
                'ordering': ['-date_updated', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IncomingProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Quantity')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Received')),
                ('incoming_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_product_items', to='inventory.incomingproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_product_items', to='purchase.product')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_product_items', to='purchase.unitofmeasure')),
            ],
        ),
    ]
