# Generated by Django 5.0.6 on 2025-07-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_locationstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapitem',
            name='adjusted_quantity',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentitem',
            name='current_quantity',
        ),
    ]
