# Generated by Django 5.0.6 on 2025-05-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_scrap_adjustment_type_deliveryorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.deliveryorder'),
        ),
    ]
