# Generated by Django 5.0.6 on 2025-06-03 06:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_scrap_adjustment_type_incomingproduct_and_more'),
        ('purchase', '0013_remove_povendorquoteitem_po_vendor_quote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingproductitem',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='backorder_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='inventory.incomingproduct'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('canceled', 'Canceled')], default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='incomingproduct',
            name='incoming_product_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incomingproduct',
            name='receipt_type',
            field=models.CharField(choices=[('vendor_receipt', 'Vendor Receipt'), ('manufacturing_receipt', 'Manufacturing Receipt'), ('internal_transfer', 'Internal Transfer'), ('returns', 'Returns'), ('scrap', 'Scrap')], default='vendor_receipt'),
        ),
        migrations.AlterField(
            model_name='incomingproductitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expected Quantity'),
        ),
        migrations.AlterField(
            model_name='incomingproductitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Received'),
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('shipping_policy', models.TextField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('ready', 'Ready'), ('done', 'Done')], default='draft', max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_orders', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_deliver', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_items', to='inventory.deliveryorder')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='purchase.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_of_return', models.DateField(default=django.utils.timezone.now)),
                ('reason_for_return', models.TextField()),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('return_warehouse_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_warehouse', to='inventory.location')),
                ('source_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_document', to='inventory.deliveryorder')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_delivery_location', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.PositiveIntegerField()),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('delivery_order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order_return_items', to='inventory.deliveryorderreturn')),
                ('returned_product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_items', to='purchase.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnIncomingProduct',
            fields=[
                ('unique_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('reason_for_return', models.TextField()),
                ('returned_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now=True)),
                ('source_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_incoming_product', to='inventory.incomingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnIncomingProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_be_returned', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_product_items', to='purchase.product')),
                ('return_incoming_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_incoming_product_items', to='inventory.returnincomingproduct')),
            ],
        ),
    ]
