# Generated by Django 5.0.6 on 2025-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_incomingproduct_backorder_of_backorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='source_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
