# Generated by Django 5.0.6 on 2025-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_scrap_adjustment_type_incomingproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('canceled', 'Canceled')], default='draft', max_length=15),
        ),
    ]
