# Generated by Django 5.0.6 on 2025-05-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_incomingproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingproductitem',
            name='unit_of_measure',
        ),
    ]
