# Generated by Django 5.0.6 on 2025-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmove_source_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('RETURN', 'Return'), ('INTERNAL', 'Internal Transfer'), ('ADJUSTMENT', 'Inventory Adjustment'), ('SCRAP', 'Scrap'), ('BACKORDER', 'Back Order')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
