# Generated by Django 5.0.6 on 2025-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_incomingproductitem_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorderreturn',
            name='source_location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
