# Generated by Django 5.0.6 on 2025-05-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_productline_delivery_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='quantity',
            new_name='quantity_to_deliver',
        ),
    ]
