# Generated by Django 5.0.6 on 2025-05-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_incomingproductitem_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproductitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity Received'),
        ),
    ]
