# Generated by Django 5.0.6 on 2025-05-15 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_quantity_productline_quantity_to_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
