# Generated by Django 5.0.6 on 2025-08-27 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_stockmove_move_type_alter_stockmove_reference'),
        ('purchase', '0004_alter_purchaserequestitem_estimated_unit_price_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id_number', models.PositiveIntegerField(auto_created=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('released', 'Released'), ('done', 'Done'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to='users.tenantuser')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfers_to_destination', to='inventory.location')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfers_from_source', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to='users.tenantuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Requested')),
                ('internal_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfer_items', to='inventory.internaltransfer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.product')),
            ],
        ),
    ]
