# Generated by Django 5.0.6 on 2025-08-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_internaltransfer_internaltransferitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproduct',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_products_to_destination', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='internaltransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('released', 'Released'), ('done', 'Done'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
    ]
