# Generated by Django 5.0.6 on 2025-05-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_incomingproductitem_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproductitem',
            name='expected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expected Quantity'),
        ),
    ]
