# Generated by Django 5.0.6 on 2025-05-16 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_productline_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('source_document', models.CharField(editable=False, max_length=50)),
                ('date_of_return', models.DateField(default=django.utils.timezone.now)),
                ('source_location', models.CharField(max_length=255)),
                ('reason_for_return', models.TextField()),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.deliveryorder')),
                ('return_warehouse_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_warehouse', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('returned_quantity', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_records', to='inventory.returnrecord')),
            ],
        ),
    ]
