# Generated by Django 5.0.6 on 2025-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_returnrecord_returnproductline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproductline',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
