# Generated by Django 5.0.6 on 2025-05-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_deliveryorder_deliveryorderitem_deliveryorderreturn_and_more'),
        ('purchase', '0012_purchaseorder_destination_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnIncomingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason_for_return', models.TextField()),
                ('returned_date', models.DateField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_incoming_product', to='inventory.incomingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnIncomingProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_product_items', to='purchase.product')),
                ('return_incoming_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_incoming_product_items', to='inventory.returnincomingproduct')),
            ],
        ),
    ]
