# Generated by Django 5.0.6 on 2025-06-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_returnincomingproduct_returnincomingproductitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='backorder_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='inventory.incomingproduct'),
        ),
        migrations.AddField(
            model_name='incomingproduct',
            name='incoming_product_id',
            field=models.CharField(default=1, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
