# Generated by Django 5.0.6 on 2025-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_incomingproduct_backorder_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='incomingproduct',
            name='incoming_product_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
