# Generated by Django 5.1.2 on 2024-10-30 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_tenant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='otp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='otp_requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenant',
            name='otp_verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.tenant'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('allow_multiple_tenants', models.BooleanField(default=False)),
                ('max_tenants', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
