# Generated by Django 5.0.6 on 2024-10-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_tenant_created_by_tenant_is_verified_tenant_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
