# Generated by Django 5.0.6 on 2025-06-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_application_applicationmodule_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodule',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_modules', to='registration.application'),
        ),
    ]
