# Generated by Django 5.0.6 on 2025-06-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_applicationmodule_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodule',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationModule',
        ),
    ]
