# Generated by Django 5.0.6 on 2025-07-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_zip_code_companyprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
