# Generated by Django 5.0.6 on 2025-06-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
