# Generated by Django 5.0.6 on 2025-06-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_delete_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='address',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.companyprofile')),
            ],
        ),
    ]
